### ISSUE TITLE
Expanded keyboard firmware

### ISSUE THREAD

**Issue by hasn0life** [Xinyuan-LilyGO/T-Deck#16]
I added some functionality to the keyboard firmware, I figured I'd link it here in case you or other people want to take from it or add to it. Thanks! https://github.com/hasn0life/t-deck-keyboard-ex/tree/main

**Comment by laulin** [comment]
Hello hasn0life, it is very cool. A more "blackberry look and feel" with key holding would be perfect but it would break API (single byte per key).

**Comment by contractorwolf** [comment]
@hasn0life does that mean I could control the keyboard backlight by just using #define keyboard_BL_PIN  9?  is that documented anywhere else?
