### ISSUE TITLE
IO pins 28 to 30 

### ISSUE THREAD

**Issue by jharvey** [Xinyuan-LilyGO/T-Deck#17]
Could ESP32-S3 pins 28 to 30 and other currently non-terminated pins be routed to some pads or generic via(s), perhaps a header of some kind. This would make it easier to expand the options of this PCB.

**Comment by lewisxhe** [comment]
Can't . 
![image](https://github.com/Xinyuan-LilyGO/T-Deck/assets/22990954/907b0701-5756-43f6-bd3c-d0124cda0c9c)
