### ISSUE TITLE
T-Deck keep restarting while using meshtastic

### ISSUE THREAD

**Issue by litasio** [Xinyuan-LilyGO/T-Deck#18]
Hello,

I'm wondering if it is a faulty t-deck or something that I can fix on my own. After trying different stable versions from meshtastic, T-Deck keeps crashing.

**Comment by 0015** [comment]
@litasio Which version are you using? I tried it with 2.2.16 and worked great. https://youtu.be/wmGBAGr9dNA?si

**Comment by acidvegas** [comment]
> Hello,
> 
> I'm wondering if it is a faulty t-deck or something that I can fix on my own. After trying different stable versions from meshtastic, T-Deck keeps crashing.

any custom settings you turned on? That would really help. I know tls with mqtt was causing reboots.

**Comment by 7Zorro7** [comment]
i was having same issues. started using ripple has alot better potential
