### ISSUE TITLE
Replacement screen 

### ISSUE THREAD

**Issue by startung** [Xinyuan-LilyGO/T-Deck#19]
I have broke the screen on my t-deck v1.1. Is it possible to order a replacement?

**Comment by lewisxhe** [comment]
Contact the seller, this issue is not within the scope of discussion on github

**Comment by startung** [comment]
I agree github is not the place for this, but posting here is the method of support suggested by lilygo:

![2024-03-26_08-01](https://github.com/Xinyuan-LilyGO/T-Deck/assets/717612/38c8bde9-c98c-449c-92c3-63182be2600d)

For reference, I found one that worked on aliexpress described as an ST7789 capacitive IPS screen with reference HC28030-DCT
