### ISSUE TITLE
UnitTest Example not Compiling

### ISSUE THREAD

**Issue by tomvdb** [Xinyuan-LilyGO/T-Deck#2]
Hi There,

All examples seems to compiling and working fine, except for the UnitTest example. It seems to be looking for lv_conf.h

All libraries are correctly installed. Maybe a file is missing ?

`In file included from c:\users\admin\documents\arduino\libraries\lvgl\src/misc/lv_log.h:16,
                 from c:\users\admin\documents\arduino\libraries\lvgl\lvgl.h:25,
                 from C:\Users\admin\Documents\Arduino\libraries\lvgl\src/lvgl.h:17,
                 from C:\temp\T-Deck-master\examples\UnitTest\UnitTest.ino:13:
c:\users\admin\documents\arduino\libraries\lvgl\src\lv_conf_internal.h:41:18: fatal error: ../../lv_conf.h: No such file or directory
         #include "../../lv_conf.h"                /*Else assume lv_conf.h is next to the lvgl folder*/
                  ^~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board ESP32S3 Dev Module.
`

**Comment by lewisxhe** [comment]
Move ` lvgl/lv_conf.h` into the `libraries` directory.
![image](https://github.com/Xinyuan-LilyGO/T-Deck/assets/22990954/a1e50096-5758-475d-a935-ec1c70e7d2d6)

**Comment by tomvdb** [comment]
Thank you :)
