### ISSUE TITLE
Does the T-Deck have an SNA connector for an external antenna?

### ISSUE THREAD

**Issue by jdcrunchman** [Xinyuan-LilyGO/T-Deck#20]
I'm trying to decide if I want to buy the unit.   But in looking at the photo of the unit,   I don't see any place I can connect my antenna to it.

Perhaps this is not the unit I can use.    I called your China office,  but they apparently didn't know much about the product.

Thanx
John D.

**Comment by startung** [comment]
On mine (t-deck v1.1), for the Lora module there is a uFL/IPEX connector - you can get uFL to SMA convertors. The wifi uses the internal wifi antenna of the ESP32-S3-WROOM-1 module. To get an external antenna for the wifi, I think you would have to desolder the module and replace it with the ESP32-S3-WROOM-1U, which has an IPEX connector.
![t-deck](https://github.com/Xinyuan-LilyGO/T-Deck/assets/717612/a6d45296-f1ca-4944-9819-8fca8218317b)
