### ISSUE TITLE
T-Deck 433 Mhz Bricked

### ISSUE THREAD

**Issue by Txcspm** [Xinyuan-LilyGO/T-Deck#21]
T-Deck 433 Mhz stuck in boot loop, bricked during flashing to newest version and will not turn respond.

Blue LED above RW1 turns on when powered by an external power source, but not battery. Computer will not recognize com port when plugged in and nothing appears on screen.

**Comment by lewisxhe** [comment]
Try to hold down the trackball on the front, press it down, and then plug in the USB to see if the port displays normally.

**Comment by Txcspm** [comment]
No luck unfortunately. Still not recognized as a com port or UART bridge
