### ISSUE TITLE
Antenna connector ripped.

### ISSUE THREAD

**Issue by mirkokral** [Xinyuan-LilyGO/T-Deck#25]
My antenna connector ripped after trying to swap from the default to a better antenna.
![2024-04-07-08-55-25-364-EDIT](https://github.com/Xinyuan-LilyGO/T-Deck/assets/75212488/0902b88a-bafe-4beb-aa82-c25ee513aef5)
Is there any way I can reconnect the antenna (original or better) or maybe fix the connector?

Sincerely, Mirko

**Comment by lewisxhe** [comment]
The PCB cannot be repaired. You can only solder the antenna directly on the LoRa module.
