### ISSUE TITLE
Display viewing angle and mounting direction

### ISSUE THREAD

**Issue by PeterAJansen** [Xinyuan-LilyGO/T-Deck#3]
Hi there, 

I love the idea of this device.  But, I just tried mine out, and (a) the display has a very poor viewing angle, and (b) the viewing angle is mounted horizontally instead of vertically.  That means the only good way to view the screen is from the right, and unless you hold it at a very sharp angle, your eyes see two very different pictures.  It's driving my eyes crazy, and makes it unusable for me.  I hope you switch to a much better display on the next revision.

best wishes,
Peter

**Comment by lewisxhe** [comment]
Thank you, the screen has been replaced with another brand

**Comment by PeterAJansen** [comment]
The original purchasers should have their devices replaced.  This is not a usable product.

![IMG_3082](https://github.com/Xinyuan-LilyGO/T-Deck/assets/3813268/84b3867d-b8f6-4b07-a4b3-73c537a1d75f)
