### ISSUE TITLE
Hall effect sensor

### ISSUE THREAD

**Issue by laulin** [Xinyuan-LilyGO/T-Deck#31]
Hello,

While I was reading schematic, I discovered four hall effect sensor (UZ1-4, IC : AN4884). I didn't find them on the PCB; I tried to read G_S (Pin 15) with analog pin , played with a magnet over the PCB but nothing. Do you have more infor about these sensors ?

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/T-Deck/blob/36841457bf1c4f9a6e88c9de2199f6ff132885a5/examples/UnitTest/UnitTest.ino#L781
