### ISSUE TITLE
Can the running firmware communicate to the keyboard controller?

### ISSUE THREAD

**Issue by acidvegas** [Xinyuan-LilyGO/T-Deck#32]
Trying to figure out what PIN is matched with the keyboard backlight. I made a screen inactivity timeout, but the keyboard backlight remains on for it. Anyone have some insight?

**Comment by lewisxhe** [comment]
The default firmware does not have this function. The source code of the keyboard is here. You can modify it according to your needs. https://github.com/Xinyuan-LilyGO/T-Deck/tree/master/examples/Keyboard_ESP32C3
