### ISSUE TITLE
Cant find the documentation for this board that includes any available GPIO pins

### ISSUE THREAD

**Issue by contractorwolf** [Xinyuan-LilyGO/T-Deck#33]
does anyone have the PDF documentation document somewhere?
thx

**Comment by lewisxhe** [comment]
This board has only two available GPIOs, which are the two on the Grove socket, GPIO43 and GPIO44.

**Comment by contractorwolf** [comment]
i was more trying to figure out if there was a way to turn the keyboard backlight on/off programmatically

**Comment by lewisxhe** [comment]
The default firmware does not have this function. The source code of the keyboard is here. You can modify it according to your needs. https://github.com/Xinyuan-LilyGO/T-Deck/tree/master/examples/Keyboard_ESP32C3

**Comment by contractorwolf** [comment]
how do i change the software running on the keyboard? @lewisxhe

**Comment by lewisxhe** [comment]
The keyboard is controlled by ESP32C3, you need to recode C3 using a USB2TTL
![image](https://github.com/Xinyuan-LilyGO/T-Deck/assets/22990954/3daab832-5c0e-43bf-9ca5-20a54b5ef4f6)
