### ISSUE TITLE
UnitTest.ino fails to compile. Missing kinetis.h

### ISSUE THREAD

**Issue by maria3748** [Xinyuan-LilyGO/T-Deck#39]
I am trying to compile the UnitTest.ino example.  I think I have followed all of the instructions. I get the following error sequence:
In file included from /home/dj/Arduino/libraries/Audio_-_Adafruit_Fork/analyze_fft256.h:31,
                 from /home/dj/Arduino/libraries/Audio_-_Adafruit_Fork/Audio.h:66,
                 from /home/dj/T-Deck/Xinyuan-LilyGO-T-DeckFull/Xinyuan-LilyGO-T-Deck-846705f/examples/UnitTest/UnitTest.ino:26:
/home/dj/Arduino/libraries/Audio_-_Adafruit_Fork/AudioStream.h:71:10: fatal error: kinetis.h: No such file or directory
 #include "kinetis.h"
          ^~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

**Comment by lewisxhe** [comment]
This repository does not use the Audio-_Adafruit_Fork library.
