### ISSUE TITLE
Grove Set Question

### ISSUE THREAD

**Issue by abileneaugie** [Xinyuan-LilyGO/T-Deck#40]
While removing the Grove set to solder on a GPS module directly I somehow removed the solder pad for the RX pin.   Is there an alternative spot on the board that I can solder to for RX pin?

**Comment by lewisxhe** [comment]
RX is connected to the RX Pin of ESP. You can see from the manual that it is connected here.
![image](https://github.com/user-attachments/assets/6f3a8771-577b-4de9-a053-864dbc19f754)
