### ISSUE TITLE
Which board should be used for LiliGo T-keyboard

### ISSUE THREAD

**Issue by kwccoin** [Xinyuan-LilyGO/T-Deck#41]
For both PlatformIO and Arduino, you have only 

- LilyGo T-DIsplay
- LilyGo T-Dislay-S3

There is no T-keyboard which I believed is C3.  What should I do?

**Comment by lewisxhe** [comment]
![image](https://github.com/user-attachments/assets/45cb2bcf-7d6c-4179-9515-2ea56dd28579)

**Comment by kwccoin** [comment]
Thanks.  It will be ESP32C3 Dev module.

**Comment by kwccoin** [comment]
Strange ... the doc said it is C3 and even the message said it is "Keyboard C3" but I got this error:

A fatal error occurred: This chip is ESP32-S3 not ESP32-C3. Wrong --chip argument?
Failed uploading: uploading error: exit status 2

Also if I do this upload successfully, where to find the LoRa pgm/module/... which is currently running under

**Comment by lewisxhe** [comment]
![image](https://github.com/user-attachments/assets/2e0ea049-1de0-419a-885b-88cfa707a4af)
Need external USB2TTL to be connected to the programming port instead of TYPE-C

**Comment by kwccoin** [comment]
THanks.  How to restore to this LoRA interface after I successfully upload my scratch.  It will replace it I assumed?  

I do not find in your example any LoRa interface .ino.

**Comment by lewisxhe** [comment]
What is LoRa interface?

**Comment by kwccoin** [comment]
It is a module that is optional but installed in my LilyGO-T keyboard.  Mine is 433MHz and the label said

LILYGO
433/470Mhz
Model: LoRa32
SX1262

I believed it is about communication.

**Comment by kwccoin** [comment]
> ![image](https://private-user-images.githubusercontent.com/22990954/363386969-2e0ea049-1de0-419a-885b-88cfa707a4af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNzYwNDEsIm5iZiI6MTcyNTA3NTc0MSwicGF0aCI6Ii8yMjk5MDk1NC8zNjMzODY5NjktMmUwZWEwNDktMWRlMC00MTlhLTg4NWItODhjZmE3MDdhNGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDAzNDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmY2JlM2Q1M2Y5Mjc3ZGNhZjA4MmMwM2I3ZDM1NTA0ZWU2MmRmYTRkNDFiN2I2NTY2ZDgwNzM5YjM1Mzk3MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yB0QzPwuYuhRntcj1OGwKLK-LF69usRlZEJD4S8zWWI) Need external USB2TTL to be connected to the programming port instead of TYPE-C

Just place order to get those cables ... For the LiliGO LoRa module, how to restore it is still awaiting your answer.  Thanks for the speedy support.

**Comment by lewisxhe** [comment]
[UnitTest](https://github.com/Xinyuan-LilyGO/T-Deck/tree/master/examples/UnitTest) contains LoRa examples
