### ISSUE TITLE
UnitTest.ino.cpp] TypeError : unsupported operand type(s) for -: 'float' and 'NoneType

### ISSUE THREAD

**Issue by varlocko** [Xinyuan-LilyGO/T-Deck#44]
The following occurs 

Processing T-Deck-915M (platform: espressif32@6.3.0; board: T-Deck; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/T-Deck.html
PLATFORM: Espressif 32 (6.3.0) > LilyGo T-Decl(16M Flash 8M OPI PSRAM )
HARDWARE: ESP32S3 240MHz, 320KB RAM, 16MB Flash
DEBUG: Current (esp-builtin) On-board (esp-builtin) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20009.0 (2.0.9) 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5 
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
Converting UnitTest.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 41 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ES7210 @ 1.0.0
|-- TouchLib @ 0.0.2
|-- ESP32-audioI2S @ 2.0.6
|-- lvgl @ 8.3.0-dev
|-- RadioLib @ 5.3.0
|-- SD @ 2.0.0
|-- SPI @ 2.0.0
|-- TFT_eSPI @ 2.5.22
|-- TinyGPSPlus @ 1.0.3
|-- WiFi @ 2.0.0
Building in release mode
******* [examples\UnitTest\UnitTest.ino.cpp] TypeError : unsupported operand type(s) for -: 'float' and 'NoneType'****
================================================================================================= [FAILED] Took 287.41 seconds =================================================================================================

Environment    Status    Duration
-------------  --------  ------------
T-Deck-915M    FAILED    00:04:47.412
============================================================================================ 1 failed, 0 succeeded in 00:04:47.412 ============================================================================================

**Comment by lewisxhe** [comment]
This problem seems to be a problem with the platformio environment. You can try compiling an empty sketch.
