### ISSUE TITLE
Missing file?!?

### ISSUE THREAD

**Issue by sascha-hemi** [Xinyuan-LilyGO/T-Deck#47]
Hi,

i become the following error: T-Deck/examples/Touchpad/Touchpad.ino:12:10: fatal error: TouchDrvGT911.hpp: No such file or directory
Where can i find this file?

Greetings
Sascha

**Comment by lewisxhe** [comment]
Added https://github.com/Xinyuan-LilyGO/T-Deck/tree/master/lib/SensorsLib
