### ISSUE TITLE
Reset Cap Touch

### ISSUE THREAD

**Issue by mattcalhoun1** [Xinyuan-LilyGO/T-Deck#50]
Hi, is there a pin mapped for resetting the cap touch for T-Deck? I didn't see a pin mapped, so i also looked for documentation on how to do it via iic, but didn't see that.

I noticed that often after a restart triggered by firmware or triggered by flashing, the touch us unresponsive until i slide the power switch off and back on.

I'm currently working on T-Deck, but will be on t-deck plus very soon, so my question is for both.

Thanks

**Comment by lewisxhe** [comment]
There is no reset pin, there is no way to solve this problem, you must power off and restart.

**Comment by mattcalhoun1** [comment]
thanks
