### ISSUE TITLE
Push TFT eSPI UserSetup files to official TFT eSPI repo

### ISSUE THREAD

**Issue by hpsaturn** [Xinyuan-LilyGO/T-Deck#51]
## Summary

These board is awesome guys. Congrats for nice job! The only ugly thing is that it has the dependencies burned in code or these are included only this repo. I can see that the official TFT eSPI already have some LilyGO boards included. Is possible maybe try to upload the current T-Deck UserSetup via to the official repo? to remove the local dependency?

Of course will be really nice also push the other configs of the other libraries or improve the PlatformIO ini file included in this repo, to would uses the fixed dependencies and not the local libraries.

Thanks in advance.

**Comment by lewisxhe** [comment]
Fixed local dependencies are just to help beginners get started quickly and troubleshoot problems quickly.
As for whether to push TFT_eSPI upstream, it depends on whether Bodmer continues to maintain this project. Bodmer hasn't maintained this project for a while, and all PRs are stuck there.

**Comment by hpsaturn** [comment]
Thanks for you feedback. It's true it that you mentioned. I'm going to close this issue and also put here a possible solution or example using LGFX Library. In this project that we included this library like a third party dependency without copy the library into itself project, for  your T-Deck board:

https://github.com/jgauchia/IceNav-v3/tree/devel
