### ISSUE TITLE
Replacing the ESP32 SMD with one that has a IPEX connector

### ISSUE THREAD

**Issue by FBIGlowie** [Xinyuan-LilyGO/T-Deck#53]
Hello,

Would it be possible to replace the ESP32 module with one that has a IPEX connector such as [ESP32-S3-WROOM-1U-N16R8](https://www.mouser.com/ProductDetail/Espressif-Systems/ESP32-S3-WROOM-1U-N16R8?qs=Li%252BoUPsLEns6V0Pr5KRJtw%3D%3D)?

This specific model contains the same SoC and pinout as the one already inside the T-Deck.

Thanks

**Comment by lewisxhe** [comment]
Of course, they are the same.

**Comment by FBIGlowie** [comment]
Thanks!!
