### ISSUE TITLE
Joining the TTN network via example LoRaWAN_Starter.ino results in RX1 and RX2 window timeouts for T-Deck

### ISSUE THREAD

**Issue by predictitai** [Xinyuan-LilyGO/T-Deck#57]
I use the T-deck and this repository in VSCode and platform.io.

I am trying to connect to the thingsnetwork (ttn) in europe (868.1Mhz) and provided the JoinEUI, DevEUI, AppKey and NwkKey in config.h. I see in the log that the join was succesful and that an awknowledgement has been sent to the device. Directly after, i receive timeouts for both windows Rx1 and Rx2.

RADIOLIB_DEBUG_PROTOCOL_PRINTLN("Opening Rx%d window (%d ms timeout)... <-- Rx Delay end ", window, (int)(timeoutHost / 1000 + scanGuard / 2));

Changing the delays doesn't seem to have any effect. Also i tried the join request at different locations but the problem remains.
I also tried to play with the frequency plan settings but it always receive in a timeout; and hence the join error.

Could someone please provide me with some advice? Did anyone has this working on the T-Deck?

Hopefully someone could help me out,

Kind regards,

Anouar

**Comment by lewisxhe** [comment]
I can't answer this question for you, you can go to RadioLib and try asking it
