### ISSUE TITLE
Connecting CC1101 to LilyGo T-Deck for Frequency Scanning and LoRa Transmission

### ISSUE THREAD

**Issue by cristiantacchi** [Xinyuan-LilyGO/T-Deck#58]
Hello,
I’m considering using the LilyGo T-Deck as a portable device for a project that involves frequency scanning and data transmission. My goal is to connect a CC1101 transceiver to the T-Deck for checking different RF frequencies. I would like to display the results on the built-in screen and use LoRa for transmitting the data.

I would appreciate your advice on the following:

Is it possible to interface the T-Deck with a CC1101 transceiver?
Are there any known compatibility issues or potential limitations I should be aware of?
Any recommendations or examples on how to implement this setup?
Thanks in advance for your help

**Comment by lewisxhe** [comment]
The common modulation methods of CC1101 are FSK, etc., while SX1262 mainly uses LoRa modulation. Due to the different modulation methods, they are incompatible in baseband signal processing.
