### ISSUE TITLE
REQ: T-Deck - Simple "hello world" example!?

### ISSUE THREAD

**Issue by IHateNameStealers** [Xinyuan-LilyGO/T-Deck#59]
Any chance of getting a simple 'hello world' example for the T-Deck ESP32-S3 ?

Thank you.

**Comment by acidvegas** [comment]
Have you looked at the [examples](https://github.com/Xinyuan-LilyGO/T-Deck/tree/master/examples) directory?

**Comment by IHateNameStealers** [comment]
Yes I did, but the only thing coming close to a "Hello world" is the UnitTest, and that is way over my head.

**Comment by lewisxhe** [comment]
You have to know that T-Deck uses bus sharing, UnitTest is the most comprehensive simple demonstration, although it is long. . I added a simple example of a screen.

**Comment by IHateNameStealers** [comment]
Thank you for adding the "hello world" example. This will really help me!
