### ISSUE TITLE
Can't completely load any Audio example

### ISSUE THREAD

**Issue by richonguzman** [Xinyuan-LilyGO/T-Deck#63]
tried using the "Audio.h" for playing a mp3 file through T-deck speaker, but cant find a way to even import libraries needed on platformio to make use of the speaker play.

any small guide as which library to use?

**Comment by lewisxhe** [comment]
All examples need to use the library copy in the lib directory

“Audio.h” is here
https://github.com/Xinyuan-LilyGO/T-Deck/tree/master/lib/ESP32-audioI2S

**Comment by richonguzman** [comment]
> Copies of all used example libraries are placed in the lib directory
> 
> “Audio.h” is here https://github.com/Xinyuan-LilyGO/T-Deck/tree/master/lib/ESP32-audioI2S

should this also work if using Platformio instead of Arduino IDE ?

**Comment by lewisxhe** [comment]
Of course it works. There is no difference between the two except the way they are built.

**Comment by richonguzman** [comment]
I copy all the "ESP32-audioI2S" folder into /lib folder of my project.

then I compile in Platformio with this:

`
#include "Audio.h"
#include "FS.h"


#ifdef HAS_I2S
   
    namespace AUDIO_Utils {

        void setup() {
            // nothing yet
        }

    }

#endif`


I get :

/Users/myUserName/.platformio/packages/framework-arduinoespressif32@3.20009.0/libraries/SD_MMC/src/SD_MMC.h:21:10: fatal error: FS.h: No such file or directory

even adding: #include "FS.h" it still get this error and could not go further

**Comment by lewisxhe** [comment]
Post your platfromio.ini

**Comment by richonguzman** [comment]
[env:ttgo_t_deck_plus]
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
platform = espressif32 @ 6.3.1
board_build.partitions = huge_app.csv
monitor_filters = esp32_exception_decoder
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
build_flags =
	${common.build_flags}
        -Werror -Wall
	${common.usb_flags}
	-D TTGO_T_DECK_PLUS
	-D BOARD_HAS_PSRAM
	-D HAS_SX1262
	-D GPS_BAUDRATE=38400
	-D HAS_TFT
    -D USER_SETUP_LOADED
    -D ST7789_DRIVER
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_INVERSION_ON
    -D TFT_MISO=38
    -D TFT_MOSI=41
    -D TFT_SCLK=40
    -D TFT_CS=12
    -D TFT_DC=11
    -D TFT_RST=-1
	-D TFT_BUSY=-1
	-D TFT_BL=42
	-D TFT_BACKLIGHT_ON=1
    -D TOUCH_CS=-1
    -D LOAD_GLCD
    -D LOAD_FONT2
    -D LOAD_FONT4
    -D LOAD_FONT6
    -D LOAD_FONT7
    -D LOAD_FONT8
    -D SPI_FREQUENCY=40000000
    -D SPI_READ_FREQUENCY=16000000
lib_deps =
	adafruit/Adafruit BusIO @ 1.16.1
	adafruit/Adafruit Unified Sensor @ 1.1.14
	adafruit/Adafruit BME280 Library @ 2.2.4
	adafruit/Adafruit BMP280 Library @ 2.6.8
	adafruit/Adafruit BME680 Library @ 2.0.4
	bblanchon/ArduinoJson @ 6.21.3
	h2zero/NimBLE-Arduino @ 1.4.1
	jgromes/RadioLib @ 6.6.0
	mathieucarbou/AsyncTCP @ 3.2.5
	mathieucarbou/ESPAsyncWebServer @ 3.2.3
	mikalhart/TinyGPSPlus @ 1.0.3
	paulstoffregen/Time @ 1.6.1
	peterus/esp-logger @ 1.0.0
	shaggydog/OneButton @ 1.5.0	
	bodmer/TFT_eSPI @ 2.5.43

**Comment by lewisxhe** [comment]
Yours is too complicated, I added a simple playback example

**Comment by lewisxhe** [comment]
You can try adding this in lib_deps = esphome/ESP32-audioI2S@2.0.6

**Comment by richonguzman** [comment]
> You can try adding this in lib_deps = esphome/ESP32-audioI2S@2.0.6

added "esphome/ESP32-audioI2S @ 2.0.6" in lib_depts (and deleted the other from "/lib")

compiled just to test without adding any more code than before and same:

"In file included from /Users/ricardoguzman/.platformio/packages/framework-arduinoespressif32@3.20009.0/libraries/SD_MMC/src/SD_MMC.cpp:16:
/Users/ricardoguzman/.platformio/packages/framework-arduinoespressif32@3.20009.0/libraries/SD_MMC/src/SD_MMC.h:21:10: fatal error: FS.h: No such file or directory"


#include "FS.h"
          ^~~~~~
compilation terminated.
Compiling .pio/build/ttgo_t_deck_plus/lib735/SPIFFS/SPIFFS.cpp.o
*** [.pio/build/ttgo_t_deck_plus/libabd/SD_MMC/SD_MMC.cpp.o] Error 1

**Comment by lewisxhe** [comment]
It seems that there is a problem with the platformio index and it cannot find the correct dependencies.

There is no problem running it alone

**Comment by richonguzman** [comment]
> It seems that there is a problem with the platformio index and it cannot find the correct dependencies.
> 
> There is no problem running it alone

how could I add this "alone"??

**Comment by lewisxhe** [comment]
In my example, it is normal
https://github.com/Xinyuan-LilyGO/T-Deck/commit/7aa23db0230ce803f3efe6043ed15ad7d1eeb431

I was wondering why this avatar looks so familiar, it turns out to be you again. Hahahaha

I just tested it in your project, please fork a fork, comment out the following header file, and it can be compiled normally. This must be caused by a problem with the reference of platformio

![image](https://github.com/user-attachments/assets/0cefa556-653b-488d-b320-3087f9f482ad)

**Comment by richonguzman** [comment]
> In my example, it is normal [7aa23db](https://github.com/Xinyuan-LilyGO/T-Deck/commit/7aa23db0230ce803f3efe6043ed15ad7d1eeb431)
> 
> I was wondering why this avatar looks so familiar, it turns out to be you again. Hahahaha
> 
> I just tested it in your project, please fork a fork, comment out the following header file, and it can be compiled normally. This must be caused by a problem with the reference of platformio
> 
> ![image](https://private-user-images.githubusercontent.com/22990954/386021411-0cefa556-653b-488d-b320-3087f9f482ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTY2OTYsIm5iZiI6MTczMTU1NjM5NiwicGF0aCI6Ii8yMjk5MDk1NC8zODYwMjE0MTEtMGNlZmE1NTYtNjUzYi00ODhkLWIzMjAtMzA4N2Y5ZjQ4MmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAzNTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyODg1N2YzOWNmYzVmZjIyY2QyM2M2ODU0YTY2YWU3ZWQ0YzQ2MjljZDQ3YTJiNGU0NGZkYzI2Mjg1YWVjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1XbdhyrziIHGt4ttgI9EhulpxPKRSqGmBGCXxgajC44)

sorry to push so much lately but I'm willing to make lots of upgrades for this!!! 😃 


so:
1) library import on platformio.ini is now : esphome/ESP32-audioI2S @ 2.0.7
2) edited the library without "SD_MMC.h" and others.
3) have to add "es7210" folder from T-Deck main to my own /lib

now it can be added a mp3 and plays:

but I have 2 issues:
1) is the quality of the mp3 defined as a minimum to be listened fine?
2) when the board finishes playing the audio it make a noise when it stops

**Comment by lewisxhe** [comment]
1. By looking at the source code, we can see that the volume can be set to 0~21
https://github.com/Xinyuan-LilyGO/T-Deck/blob/7aa23db0230ce803f3efe6043ed15ad7d1eeb431/lib/ESP32-audioI2S/src/Audio.cpp#L4515
2. What does it mean when you make a sound when you stop? How do you run it?

**Comment by richonguzman** [comment]
> 2. What does it mean when you make a sound when you stop? How do you run it?

`void playMP3(const String& filename) {
            bool findMp3 = false;
            findMp3 = audio.connecttoFS(SPIFFS, filename.c_str());
            if (findMp3) {
                audio.setVolume(21);
                while (audio.isRunning()) {
                    audio.loop();
                //    delay(3);
                }
                /*audio.setVolume(0);
                delay(10);
                audio.stopSong();
                delay(50);*/
                //audio.stop();
            }
        }`

**Comment by lewisxhe** [comment]
I didn't notice any popping sounds when I ran it. Does this have anything to do with the audio file?
