### ISSUE TITLE
'b' character is sent at the same time when backlight is toggled with alt+b.

### ISSUE THREAD

**Issue by joyel24** [Xinyuan-LilyGO/T-Deck#69]
meshtastic/firmware#5524

What do you think about this issue, should it be a good idea to fix that in the keyboard firmware ?

**Comment by lewisxhe** [comment]
Hi,@joyel24

This problem is not difficult to solve. I will fix it after I finish the work I am doing.

**Comment by joyel24** [comment]
Of course it's not difficult to fix but I mostly wanted to know your opinion about that and if you think that it's a good thing to make the changes universally...

**Comment by lewisxhe** [comment]
The problem has been fixed. All subsequent keyboard factory programs will use the fixed one.
