### ISSUE TITLE
SYM function not practical 

### ISSUE THREAD

**Issue by joyel24** [Xinyuan-LilyGO/T-Deck#70]
SYM should work like SHIFT.

Actually, for example if you want to enter multiple numbers while holding SYM, it will only work for the 1st character, the other will ignore SYM key pressed.

For example if I keep the sym key pressed then type '1234' it will write: '1ers'
It's not what we expect.

**Comment by lewisxhe** [comment]
Solve

**Comment by joyel24** [comment]
> Solve

Perfect ! Thank you 😊 Merry Christmas 🎄
